

# Language
language: node_js
node_js:
  - "node"

# Branches to build
branches:
  only:
    - master

# Build
script:
  - npm install
  - npm test

after_success:
  - npm run coverage

# Notifications
notifications:
  email:
    recipients:
      - chengkuang@gmail.com
    on_success: change
    on_failure: change
